### ISSUE TITLE
User access removed, access is now via a team

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/cla-reform-design#2]
Hi there

The user lelpalfrey had Direct Member access to this repository and access via a team.

Access is now only via a team.

You may have less access it is dependant upon the teams access to the repo.

If you have any questions, please post in [#ask-operations-engineering](https://mojdt.slack.com/archives/C01BUKJSZD4) on Slack.

This issue can be closed.

**Comment by lelpalfrey** [comment]
Hi Antony,

I've posted on the #ask-operations-engineering
<https://mojdt.slack.com/archives/C01BUKJSZD4> channels when I try to clone
a repo using

git clone ***@***.***:ministryofjustice/cla-reform-design.git


I get


Cloning into 'cla-reform-design'...

***@***.***: Permission denied (publickey).

fatal: Could not read from remote repository.


Not sure what is causing this....


Thanks,


Lel




--

[image: A picture containing background pattern Description automatically
generated]

Lel Palfrey (he/him)

Service Designer - LAA Digital

***@***.***

07701 006 364

Find me on People Finder

A flexible organisation, driven by data, led by users
